### ISSUE TITLE
more than 259 symbols in path cause total appcrash

### ISSUE THREAD

**Issue by shinji2009** [tiglat/catalog_maker#3]
hi
i was using catalog_maker 3.1.9 before and everything was fine.
few days ago i was wondering if there a new version that supported unicode and it is.
i downloaded 4.1.0 and was surprised that total crashes when accessing .lst file.
i've done some research and i found that it is because 4.1.0 and 4.0.0 make .lst files with full path even if it is more than 259 symbols.
3.1.9 cut the file path on <259 symbols so .lst and total is working but with this file data become partially useless.

tested on  latest 9.51 totalcmd - same thing

can this be fixed both ways? so the path is full and .lst is accessible?

**Comment by tiglat** [comment]
According to information from shinji2009 the problem was found on Windows 8.1.

**Comment by tiglat** [comment]
Fixed in commit https://github.com/tiglat/catalog_maker/commit/c6751385cde9d874789b19101365da600917797b
