### ISSUE TITLE
Checkbox Dir size doesn't work for directories >1TB

### ISSUE THREAD

**Issue by ivkokrajniak** [tiglat/catalog_maker#6]
With the checkbox Dir size checked this plugin stops working with Write error when reaching directory of size >1TB (previous directories are written to catalog file).
Unchecking it would be a temporary workaround.

**Comment by tiglat** [comment]
Thank you for notification. I will investigate the issue as soon as possible.

**Comment by tiglat** [comment]
Hi!

I fixed the issue. Root cause - size column width was limited to 15 chars including separators. I made this field dynamic, so I hope this problem will never happen.

Please try new version 4.1.3

**Comment by theMK2k** [comment]
✅ I took the opportunity to test this with 4.1.3 - success!
