### ISSUE TITLE
Full path with more than 259 characters leads to reported file size of 0 byte and date of 1985-01-01

### ISSUE THREAD

**Issue by theMK2k** [tiglat/catalog_maker#7]
First, thanks for this great plugin!

There seems to still be an issue with files and their full path having more than 259 characters: the reported file size is 0 byte instead of the actual file size and the date is always reported as 1985-01-01 within TotalCommander (the date in the .lst file is 1601-01-01). It looks to me as though the file itself is recognized, the detection of its size and date seems to not work properly.

I attached an .lst file (had to rename to .txt for reference. It contains a directory of 200 characters and therein one file of 50 characters (correct size and date) as well as a file of 60 characters (incorrect size and date).

Thanks for having a look!

[overshoot_259.txt](https://github.com/tiglat/catalog_maker/files/7575403/overshoot_259.txt)

**Comment by tiglat** [comment]
Thank you for report, I will work on this issue as soon as possible.

**Comment by tiglat** [comment]
Hi!

Fixed in 4.1.3. Could you please try it.

**Comment by theMK2k** [comment]
✅ re-test with 4.1.3 successful, many thanks!
